CREATE TABLE employees (
  employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  firstname VARCHAR2(50),
  lastname VARCHAR2(50),
  hire_date DATE DEFAULT sysdate,
  salary NUMBER,
  status VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
  PRIMARY KEY(employee_id)
);

