CREATE TABLE orders (
  order_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  employee_id NUMBER,
  order_date DATE DEFAULT SYSDATE,
  order_total NUMBER,
  status VARCHAR2(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'SHIPPED', 'CANCELLED')),
  CONSTRAINT orders_employee_id_fk FOREIGN KEY (employee_id) REFERENCES employees (employee_id)
);