DROP USER rrhh CASCADE;
CREATE USER rrhh IDENTIFIED BY rrhh;
GRANT CREATE SESSION, CREATE TABLE, CREATE PROCEDURE, CREATE SEQUENCE, CREATE VIEW TO rrhh;
ALTER USER rrhh QUOTA 100M ON USERS;
SELECT * FROM rrhh.employees;
