DROP USER rrhh CASCADE;
CREATE USER rrhh IDENTIFIED BY rrhh;
GRANT CREATE DEBUG, SESSION, CREATE TABLE, CREATE PROCEDURE, CREATE SEQUENCE, CREATE VIEW TO rrhh;
ALTER USER rrhh QUOTA 100M ON USERS;
SELECT * FROM rrhh.employees;


/* Participantes */

CREATE USER xiomara IDENTIFIED BY xiomara;
GRANT CREATE SESSION, CREATE TABLE, CREATE PROCEDURE, CREATE SEQUENCE, CREATE VIEW TO xiomara;
ALTER USER xiomara QUOTA 100M ON USERS;

CREATE USER isabel IDENTIFIED BY isabel;
GRANT CREATE SESSION, CREATE TABLE, CREATE PROCEDURE, CREATE SEQUENCE, CREATE VIEW TO isabel;
ALTER USER isabel QUOTA 100M ON USERS;

CREATE USER douglas IDENTIFIED BY douglas;
GRANT CREATE SESSION, CREATE TABLE, CREATE PROCEDURE, CREATE SEQUENCE, CREATE VIEW TO douglas;
ALTER USER douglas QUOTA 100M ON USERS;

CREATE USER palma IDENTIFIED BY palma;
GRANT CREATE SESSION, CREATE TABLE, CREATE PROCEDURE, CREATE SEQUENCE, CREATE VIEW TO palma;
ALTER USER palma QUOTA 100M ON USERS;

CREATE USER gabriel IDENTIFIED BY gabriel;
GRANT CREATE SESSION, CREATE TABLE, CREATE PROCEDURE, CREATE SEQUENCE, CREATE VIEW TO gabriel;
ALTER USER gabriel QUOTA 100M ON USERS;
